// Inlines the Phosphor icons listed in scripts/icon-names.txt into js/icons.js (regular + fill), no dependencies.
// Usage: node scripts/build-icons.mjs
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const PKG = '@phosphor-icons/core@2.1.1';
const root = path.join(path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/, '$1')), '..');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'phosphor-'));
try {
  const tgz = execFileSync('npm', ['pack', PKG, '--silent', '--pack-destination', tmp], {encoding: 'utf8', shell: process.platform === 'win32'}).trim().split('\n').pop();
  execFileSync('tar', ['-xzf', tgz, '-C', tmp], {cwd: tmp});
  const pkg = path.join(tmp, 'package');
  const inner = f => {
    if (!fs.existsSync(f)) throw new Error('missing icon file: ' + path.relative(pkg, f));
    return fs.readFileSync(f, 'utf8').replace(/^[\s\S]*?<svg[^>]*>|<\/svg>\s*$/g, '').trim();
  };
  const names = fs.readFileSync(path.join(root, 'scripts/icon-names.txt'), 'utf8').split(/\r?\n/).map(s => s.trim()).filter(Boolean);
  const icons = {};
  for (const n of names) icons[n] = [inner(path.join(pkg, 'assets/regular', n + '.svg')), inner(path.join(pkg, 'assets/fill', n + '-fill.svg'))];
  fs.writeFileSync(path.join(root, 'js/icons.js'), '// generated by scripts/build-icons.mjs from ' + PKG + ' (MIT, see assets/icons/PHOSPHOR-LICENSE.txt). Do not edit.\nexport const ICONS=' + JSON.stringify(icons) + ';\n');
  fs.mkdirSync(path.join(root, 'assets/icons'), {recursive: true});
  fs.copyFileSync(path.join(pkg, 'LICENSE'), path.join(root, 'assets/icons/PHOSPHOR-LICENSE.txt'));
  console.log('wrote js/icons.js with', names.length, 'icons');
} catch (e) {
  console.error(e.message);
  process.exitCode = 1;
} finally {
  fs.rmSync(tmp, {recursive: true, force: true});
}
